<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\**" />
    <EmbeddedResource Remove="DTOs\**" />
    <None Remove="DTOs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BisiPro.Contracts\BisiPro.Contracts.csproj" />
    <ProjectReference Include="..\BisiPro.Domain\BisiPro.Domain.csproj" />
    <ProjectReference Include="..\BisiPro.Shared\BisiPro.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="Common\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Features\Authentications\Queries\" />
    <Folder Include="Features\GroupMembers\Queries\" />
    <Folder Include="Features\Roles\" />
    <Folder Include="Features\Users\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
